PROCEDURE        ev_dn_transp_mgt (p_txn_code IN VARCHAR2, /*p_ref_no IN VARCHAR2,*/
   P_INVH_FLEX_06 IN VARCHAR2,P_INVH_FLEX_07 OUT VARCHAR2, P_INVH_FLEX_08 OUT VARCHAR2, P_INVH_FLEX_09 OUT VARCHAR2
)
IS

V_DESTINATION VARCHAR2(50); 
V_TRUCK_CAP NUMBER;
V_TRUCK_TYPE  VARCHAR2(50);

CURSOR C1 IS 
        SELECT MTM_DESTINATION, MTM_TRUCK_CAP, MTM_TRUCK_TYPE  
        FROM MGT_TRANSP_MASTER
        WHERE MTM_TYPE = 'DES'
        AND MTM_NO = P_INVH_FLEX_06;
        

BEGIN

    IF C1%ISOPEN THEN
       CLOSE C1;
    END IF;
    
    OPEN C1;
    FETCH C1 INTO V_DESTINATION, V_TRUCK_CAP, V_TRUCK_TYPE;
    CLOSE C1;
    
    if p_txn_code IN ('LDN','PDN') THEN
       
    P_INVH_FLEX_07 := V_DESTINATION;
    P_INVH_FLEX_08 := V_TRUCK_CAP;
    P_INVH_FLEX_09 := V_TRUCK_TYPE;
    
    END IF;
END;
