--cek pending costing orion versus legacy costing data 

SELECT FG_ITEM_CODE,
       FG_ITEM_NAME,
       FG_CONVER_COST,
       'AX' FG_ITEM_GRADE,
       FG_ITEM_SHADE,
       FG_SHADE_NAME,
       FG_CHP_ITEM_CODE,
       TO_NUMBER(RM_NORM) FG_CHP_CON_KG,
       FG_CHP_COST,
       RM_NORM * FG_CHP_COST + FG_CONVER_COST FG_COST_PER_KG,
       NULL FG_MS_BATCH_ITEM,
       SYSDATE FG_ITEM_CR_DT,
       'ADMIN' FG_ITEM_CR_UID,
       SUBSTR(FG_ITEM_CODE,1,3) FG_ITEM_TYPE,
       FG_TYPE,
       'COST' FG_BASIS,
       CYCC_LEFT_NO
FROM
(
SELECT DISTINCT ADJI_ITEM_CODE FG_ITEM_CODE, 
                item_name FG_ITEM_NAME,
                CYCC_TOP_128_DATA_VALUE FG_CONVER_COST,  
                --ADJI_GRADE_CODE_1 FG_ITEM_GRADE,
                ADJI_GRADE_CODE_2 FG_ITEM_SHADE, 
                grade_name FG_SHADE_NAME,
                CASE
                    WHEN CYCC_TOP_20_DATA_VALUE = 'SD' THEN 'REG'
                    WHEN CYCC_TOP_20_DATA_VALUE = 'RSD' THEN 'RCL'
                    WHEN CYCC_TOP_20_DATA_VALUE = 'BRT' THEN 'BRT'
                    WHEN CYCC_TOP_20_DATA_VALUE = 'FR' THEN 'FR'
                    ELSE 'NA'
                END FG_CHP_ITEM_CODE,
                CYCC_TOP_96_DATA_VALUE FG_TYPE,
                CYCC_TOP_80_DATA_VALUE PRDN_PER_DAY,
                CYCC_TOP_57_DATA_VALUE RM_NORM,
                CYCC_LEFT_NO
FROM OT_ADJ_HEAD,
     OT_ADJ_ITEM,
     om_grade_code_2,
     om_item,
     (     
     select CYCC_TOP_1_DATA_VALUE, CYCC_TOP_4_DATA_VALUE, CYCC_TOP_5_DATA_VALUE, CYCC_TOP_6_DATA_VALUE, MGTAPPS.FNC_CST_CHIPS_TYPE (CYCC_TOP_20_DATA_VALUE) CYCC_TOP_20_DATA_VALUE,  
     INITCAP(TRIM(SUBSTR(CYCC_TOP_96_DATA_VALUE,1, INSTR(CYCC_TOP_96_DATA_VALUE,' ',1,2)))) CYCC_TOP_96_DATA_VALUE, TO_NUMBER(CYCC_TOP_128_DATA_VALUE) CYCC_TOP_128_DATA_VALUE,
     CYCC_TOP_80_DATA_VALUE, 1 CYCC_TOP_57_DATA_VALUE, CYCC_LEFT_NO
     from mgtapps.CST_YARN_CALCULATION_CUR
     where cycc_prs_type = 20210800120
     AND CYCC_LEFT_NO IN (SELECT cyl_left_no
                           FROM mgtapps.cst_yarn_left l,
                                mgtapps.cst_mst_yarn y,
                                MGTAPPS.cst_mst_orion_reff_dtl d,
                                MGTAPPS.cst_mst_orion_reff_hdr h
                          WHERE l.cyl_cmy_sys_id = cmy_sys_id
                            AND cmy_item_code = cmord_item_code
                            AND UPPER (cyl_shade_code) = UPPER (cmord_item_shade)
                            AND cmorh_period_year = :P_YY
                            AND cmorh_period_month = :P_MM
                            AND cmorh_sys_id = cmord_cmorh_sys_id)     
     --AND SUBSTR(CYCC_TOP_1_DATA_VALUE,1,3) NOT IN ('ACY','ITY')     
     )
WHERE ADJI_ADJH_SYS_ID = ADJH_SYS_ID
AND TRUNC(ADJH_DT) BETWEEN '01-AUG-2026' AND '31-AUG-2026'
AND ADJH_TXN_CODE IN ('INVADJ')
--AND NVL(ADJI_RATE,0) <= 0
and ADJI_GRADE_CODE_2 = grade_code
AND ADJH_POST_STATUS IS NULL
and ADJI_ITEM_CODE = item_code (+)/*
and ADJI_ITEM_CODE = FG_ITEM_CODE (+)
AND ADJI_GRADE_CODE_1 = FG_ITEM_GRADE (+) 
AND ADJI_GRADE_CODE_2 = FG_ITEM_SHADE (+)*/
--AND ADJI_GRADE_CODE_1 in ('AX','AXa')
and ADJI_ITEM_CODE = CYCC_TOP_1_DATA_VALUE (+)
and ADJI_GRADE_CODE_2 = CYCC_TOP_5_DATA_VALUE (+)
AND CYCC_TOP_128_DATA_VALUE IS NULL
--and CYCC_TOP_1_DATA_VALUE is null
--AND ADJI_ITEM_CODE = 'PTY0000172'
--AND CYCC_TOP_96_DATA_VALUE <> FG_TYPE
--AND NVL(CYCC_TOP_127_DATA_VALUE,0) - NVL(FG_CONVER_COST,0)
--AND FG_ITEM_CODE IS NULL 
--AND (SUBSTR(ADJI_ITEM_CODE,1,3) not IN ('ACY','ITY','TPY','TTM','TTS','TTY') AND grade_name NOT LIKE 'MELANGE%')
),
(
 SELECT DISTINCT FG_CHP_ITEM_CODE CHP_ITEM_CODE, FG_CHP_COST
 FROM MGTDAT.OT_STD_COST_PRODUCTS_MGT
 WHERE FG_ITEM_CODE IS NOT NULL
 AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','TCH')
)
WHERE FG_CHP_ITEM_CODE = CHP_ITEM_CODE (+)
and FG_CONVER_COST is NULL



-- INSERT COSTING DATA TO PRODUCT COSTING TABLE

INSERT INTO MGTDAT.OT_STD_COST_PRODUCTS_MGT (FG_ITEM_CODE, FG_ITEM_NAME, FG_CONVER_COST, FG_ITEM_GRADE, FG_ITEM_SHADE, FG_SHADE_NAME, FG_CHP_ITEM_CODE, FG_CHP_CON_KG, FG_CHP_COST, FG_COST_PER_KG, FG_MS_BATCH_ITEM, FG_ITEM_CR_DT, FG_ITEM_CR_UID, FG_ITEM_TYPE, FG_TYPE, FG_BASIS)
SELECT FG_ITEM_CODE, 
       FG_ITEM_NAME,
       FG_CONVER_COST ,  
       'AX' FG_ITEM_GRADE,
       FG_ITEM_SHADE, 
       FG_SHADE_NAME,
       FG_CHP_ITEM_CODE,
       TO_NUMBER(RM_NORM) FG_CHP_CON_KG,
       FG_CHP_COST,
       RM_NORM * FG_CHP_COST + FG_CONVER_COST FG_COST_PER_KG,
       NULL FG_MS_BATCH_ITEM,
       SYSDATE FG_ITEM_CR_DT, 
       'ADMIN' FG_ITEM_CR_UID,
       SUBSTR(FG_ITEM_CODE,1,3) FG_ITEM_TYPE,
       FG_TYPE,
       'COST' FG_BASIS
FROM 
(
SELECT DISTINCT ADJI_ITEM_CODE FG_ITEM_CODE, 
                item_name FG_ITEM_NAME,
                CYCC_TOP_128_DATA_VALUE FG_CONVER_COST,  
                --ADJI_GRADE_CODE_1 FG_ITEM_GRADE,
                ADJI_GRADE_CODE_2 FG_ITEM_SHADE, 
                grade_name FG_SHADE_NAME,
                CASE
                    WHEN CYCC_TOP_20_DATA_VALUE = 'SD' THEN 'REG'
                    WHEN CYCC_TOP_20_DATA_VALUE = 'RSD' THEN 'RCL'
                    WHEN CYCC_TOP_20_DATA_VALUE = 'BRT' THEN 'BRT'
                    WHEN CYCC_TOP_20_DATA_VALUE = 'FR' THEN 'FR'
                    ELSE CYCC_TOP_20_DATA_VALUE
                END FG_CHP_ITEM_CODE,
                CYCC_TOP_96_DATA_VALUE FG_TYPE,
                CYCC_TOP_80_DATA_VALUE PRDN_PER_DAY,
                CYCC_TOP_57_DATA_VALUE RM_NORM
FROM OT_ADJ_HEAD,
     OT_ADJ_ITEM,
     om_grade_code_2,
     om_item,
     (     
     select CYCC_TOP_1_DATA_VALUE, CYCC_TOP_4_DATA_VALUE, CYCC_TOP_5_DATA_VALUE, CYCC_TOP_6_DATA_VALUE, MGTAPPS.FNC_CST_CHIPS_TYPE (CYCC_TOP_20_DATA_VALUE) CYCC_TOP_20_DATA_VALUE,  
     INITCAP(TRIM(SUBSTR(CYCC_TOP_96_DATA_VALUE,1, INSTR(CYCC_TOP_96_DATA_VALUE,' ',1,2)))) CYCC_TOP_96_DATA_VALUE, TO_NUMBER(CYCC_TOP_128_DATA_VALUE) CYCC_TOP_128_DATA_VALUE,
     CYCC_TOP_80_DATA_VALUE, 1 CYCC_TOP_57_DATA_VALUE
     from mgtapps.CST_YARN_CALCULATION_CUR
     where cycc_prs_type = 20210800120
     AND CYCC_LEFT_NO IN (SELECT cyl_left_no
                           FROM mgtapps.cst_yarn_left l,
                                mgtapps.cst_mst_yarn y,
                                MGTAPPS.cst_mst_orion_reff_dtl d,
                                MGTAPPS.cst_mst_orion_reff_hdr h
                          WHERE l.cyl_cmy_sys_id = cmy_sys_id
                            AND cmy_item_code = cmord_item_code
                            AND UPPER (cyl_shade_code) = UPPER (cmord_item_shade)
                            AND cmorh_period_year = :P_YY
                            AND cmorh_period_month = :P_MM
                            AND cmorh_sys_id = cmord_cmorh_sys_id)
     )
WHERE ADJI_ADJH_SYS_ID = ADJH_SYS_ID
AND TRUNC(ADJH_DT) BETWEEN '01-AUG-2026' AND '31-AUG-2026'
AND ADJH_TXN_CODE IN ('INVADJ')
and ADJI_GRADE_CODE_2 = grade_code
AND ADJH_POST_STATUS IS NULL
and ADJI_ITEM_CODE = item_code (+)
and ADJI_ITEM_CODE = CYCC_TOP_1_DATA_VALUE (+)
and ADJI_GRADE_CODE_2 = CYCC_TOP_5_DATA_VALUE (+)
AND CYCC_TOP_128_DATA_VALUE IS NOT NULL
) ,
(
 SELECT DISTINCT FG_CHP_ITEM_CODE CHP_ITEM_CODE, FG_CHP_COST
 FROM OT_STD_COST_PRODUCTS_MGT
 WHERE FG_ITEM_CODE IS NOT NULL
 AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH')
)
WHERE FG_CHP_ITEM_CODE = CHP_ITEM_CODE (+)
ORDER BY FG_ITEM_CODE, FG_ITEM_SHADE


-- DI COSTING DATA, PRODUCT YANG DI GENERATE ADALAH AX Grade, karena ada grade di bawahnya running procedure MGTDAT.STD_FG_VALUE_INSERT untuk menjalankan cost product dari grade yang tidak ada di costing data

--PROCEDURE UNTUK GENERATE COSTING PRODUCT dari bagian produksi
MGTDAT.STD_FG_COST_UPD_PRD

--PROCEDURE UNTUK GENERATE COSTING SESUAI GRADE
MGTDAT.STD_FG_VALUE_INSERT


--PROCEDURE RAW MATERIAL COST
MGTDAT.CHP_WAC_UPD


-- CEK PENDING COSTING WITH PRODUCT COSTING TABLE

SELECT DISTINCT ADJI_ITEM_CODE, item_name ADJI_ITEM_DESC,  
                --adji_item_desc, --remark by aam on 09 May 2016
                ADJI_GRADE_CODE_1,
                ADJI_GRADE_CODE_2, grade_name
FROM OT_ADJ_HEAD,
     OT_ADJ_ITEM,
     om_grade_code_2,
     om_item,
     OT_STD_COST_PRODUCTS_MGT
WHERE ADJI_ADJH_SYS_ID=ADJH_SYS_ID
AND TRUNC(ADJH_DT) BETWEEN '01-AUG-2026' AND '31-AUG-2026'--TRUNC(SYSDATE)
AND ADJH_TXN_CODE IN ('MBINVADJ','INVADJ','MBINVADJRP')
--AND NVL(ADJI_RATE,0) <= 0
and ADJI_GRADE_CODE_2 = grade_code
AND ADJH_POST_STATUS IS NULL
and ADJI_ITEM_CODE = item_code
and ADJI_ITEM_CODE = FG_ITEM_CODE (+)
AND ADJI_GRADE_CODE_1 = FG_ITEM_GRADE (+)
AND ADJI_GRADE_CODE_2 = FG_ITEM_SHADE (+)
and FG_COST_PER_KG is null
ORDER BY ADJI_ITEM_CODE, ADJI_GRADE_CODE_2, ADJI_GRADE_CODE_1




-- costing untuk masterbatch product

INSERT INTO OT_STD_COST_PRODUCTS_MGT(FG_ITEM_CODE, FG_ITEM_NAME, FG_ITEM_GRADE, FG_ITEM_SHADE, FG_SHADE_NAME, FG_COST_PER_KG, FG_ITEM_CR_DT, FG_ITEM_CR_UID, FG_ITEM_TYPE)
select cmch_orion_item_code FG_ITEM_CODE, ITEM_NAME FG_ITEM_NAME, 'A' FG_ITEM_GRADE, 'NL' FG_ITEM_SHADE, 'NATURAL' FG_SHADE_NAME, CMCH_COST_VALUATION, TO_DATE(SYSDATE,'DD/MM/RRRR') FG_ITEM_CR_DT, 'ADMIN' FG_ITEM_CR_UID, 'CMB' FG_ITEM_TYPE
from mgtapps.CST_MB_CONSUMP_HEAD, OM_ITEM
where cmch_period_year = :P_YEAR
and cmch_period_month = :P_MM
AND cmch_orion_item_code = ITEM_CODE  
and cmch_orion_item_code in
(
SELECT DISTINCT ADJI_ITEM_CODE
FROM OT_ADJ_HEAD,
     OT_ADJ_ITEM,
     om_grade_code_2,
     om_item,
     OT_STD_COST_PRODUCTS_MGT
WHERE ADJI_ADJH_SYS_ID=ADJH_SYS_ID
AND TRUNC(ADJH_DT) BETWEEN '01-AUG-2026' AND '31-AUG-2026'--TRUNC(SYSDATE)
AND ADJH_TXN_CODE IN ('MBINVADJ','MBINVADJRP')
--AND NVL(ADJI_RATE,0) <= 0
and ADJI_GRADE_CODE_2 = grade_code 
AND ADJH_POST_STATUS IS NULL
and ADJI_ITEM_CODE = item_code
and ADJI_ITEM_CODE = FG_ITEM_CODE (+)
AND ADJI_GRADE_CODE_1 = FG_ITEM_GRADE (+)
AND ADJI_GRADE_CODE_2 = FG_ITEM_SHADE (+)
--AND ADJI_ITEM_CODE in ('CMB0001430','CMB0001431')
and FG_COST_PER_KG is null
)



--query untuk cek costing product

SELECT DISTINCT ADJI_ITEM_CODE, item_name ADJI_ITEM_DESC,  
                ADJI_GRADE_CODE_1,
                ADJI_GRADE_CODE_2, grade_name, 
                ADJI_RATE, 
                ADJI_FLEX_01 CONV_COST, ADJI_FLEX_02 CHIP_CONSUMPTION, ADJI_FLEX_03 CHIP_COST,
                ADJI_FLEX_04 CHIP_ITEM,
                ADJI_FLEX_05 ITEM_TYPE, 
                ADJI_FLEX_06 BASIS, 
                ADJI_FLEX_07 FG_SELLING_PRICE, 
                ADJI_FLEX_08 AX_COST,
                ADJI_FLEX_09 AX_CONV_COST,
                ADJI_FLEX_10 VALUE_LOSS,
                ADJI_FLEX_11 PROD_VALUE_LOSS,
                sum(ADJI_QTY_BU) / 1000 qty, sum(ADJI_VAL) val,
                TO_CHAR(ADJH_DT,'YYYYMM') PERIOD
FROM OT_ADJ_HEAD,
     OT_ADJ_ITEM,
     om_grade_code_2,
     om_item
WHERE ADJI_ADJH_SYS_ID=ADJH_SYS_ID
AND TRUNC(ADJH_DT) BETWEEN '01-AUG-2026' AND '31-AUG-2026'
AND ADJH_TXN_CODE IN ('INVADJ','MBINVADJ','MBINVADJRP')

and ADJI_GRADE_CODE_2 = grade_code
and ADJI_ITEM_CODE = item_code
group by ADJI_ITEM_CODE, item_name, ADJI_GRADE_CODE_1, ADJI_GRADE_CODE_2, grade_name, ADJI_RATE, ADJI_FLEX_01, ADJI_FLEX_02, ADJI_FLEX_03, ADJI_FLEX_04,
         ADJI_FLEX_05, ADJI_FLEX_06, ADJI_FLEX_07, ADJI_FLEX_08, ADJI_FLEX_09, ADJI_FLEX_10, ADJI_FLEX_11, TO_CHAR(ADJH_DT,'YYYYMM')         
order by ADJI_ITEM_CODE, ADJI_ITEM_DESC, ADJI_GRADE_CODE_1, ADJI_GRADE_CODE_2





--UPDATE RATE TO 0

BEGIN
FOR I IN
(
SELECT DISTINCT ADJH_TXN_CODE, ADJH_NO, ADJH_DT, ADJI_SYS_ID, ADJI_ITEM_CODE, ADJI_GRADE_CODE_1, ADJI_GRADE_CODE_2
FROM OT_ADJ_HEAD,
     OT_ADJ_ITEM,
     OT_STD_COST_PRODUCTS_MGT
WHERE ADJI_ADJH_SYS_ID=ADJH_SYS_ID
AND TRUNC(ADJH_DT) BETWEEN '01-AUG-2026' AND '31-AUG-2026'
AND ADJH_TXN_CODE IN ('INVADJ','MBINVADJ','MBINVADJRP')
--AND NVL(ADJI_RATE,0) <= 0
AND ADJH_POST_STATUS IS NULL
and ADJI_ITEM_CODE = FG_ITEM_CODE (+)
AND ADJI_GRADE_CODE_1 = FG_ITEM_GRADE (+)
AND ADJI_GRADE_CODE_2 = FG_ITEM_SHADE (+)
--and FG_COST_PER_KG is null
) LOOP

UPDATE OT_ADJ_ITEM
SET ADJI_RATE = 0,
ADJI_VAL = 0
WHERE ADJI_SYS_ID = I.ADJI_SYS_ID;

END LOOP;

END;



--update cost product di ERP
DECLARE

M_VAL  NUMBER;

CURSOR C1 IS 
SELECT * FROM
     OT_STD_COST_PRODUCTS_MGT;
     
CURSOR C2 IS   
   SELECT ADJH_TXN_CODE, ADJH_DT, ADJI_SYS_ID, ADJI_ITEM_CODE, ADJI_GRADE_CODE_1, ADJI_GRADE_CODE_2, ADJI_QTY_BU, ADJI_RATE, 
         (ADJI_QTY_BU/1000) * ADJI_RATE AS CALRATE, ADJI_VAL, ITEM_NAME,
         FG_CONVER_COST, FG_COST_PER_KG, FG_CHP_CON_KG, FG_CHP_COST, FG_SELLING_PRICE, FG_CHP_ITEM_CODE, 
         FG_AX_COST, FG_AX_CONV_COST, FG_VALUE_LOSS, FG_PROD_VALUE_LOSS, FG_TYPE, FG_BASIS, FG_MS_BATCH_ITEM
   FROM OT_ADJ_HEAD,OT_ADJ_ITEM, OM_ITEM, OT_STD_COST_PRODUCTS_MGT
   WHERE ADJI_ADJH_SYS_ID=ADJH_SYS_ID
   AND TRUNC(ADJH_DT) BETWEEN '01-AUG-2026' AND '31-AUG-2026'
   AND ADJH_TXN_CODE IN ('INVADJ','MBINVADJ','MBINVADJRP')
  and ADJH_APPR_STATUS != 3
  AND ADJI_ITEM_CODE=ITEM_CODE
    AND ADJI_ITEM_CODE = FG_ITEM_CODE
    AND ADJI_GRADE_CODE_1 = FG_ITEM_GRADE
    AND ADJI_GRADE_CODE_2 = FG_ITEM_SHADE
  ORDER BY ADJI_ITEM_CODE; 
  
  
  BEGIN
  

  FOR R2 IN C2 LOOP

 M_VAL:=0;
 M_VAL:=ROUND((R2.ADJI_QTY_BU/1000)* R2.FG_COST_PER_KG ,7);
  UPDATE OT_ADJ_ITEM
  SET ADJI_ITEM_DESC = R2.ITEM_NAME,
      ADJI_RATE = nvl(R2.FG_COST_PER_KG,0),
      ADJI_VAL  = nvl(M_VAL,0),
      ADJI_FLEX_01 = to_CHAR(ROUND(nvl(R2.FG_CONVER_COST,0),5),'FM990D00000'),
      ADJI_FLEX_02 = to_CHAR(ROUND(nvl(R2.FG_CHP_CON_KG,0),5),'FM990D00000'),
      ADJI_FLEX_03 = to_CHAR(ROUND(nvl(R2.FG_CHP_COST,0),5),'FM990D00000'),
      ADJI_FLEX_04 = nvl(R2.FG_CHP_ITEM_CODE,''),
      ADJI_FLEX_05 = R2.FG_TYPE, 
      ADJI_FLEX_06 = R2.FG_BASIS, 
      ADJI_FLEX_07 = to_CHAR(ROUND(nvl(R2.FG_SELLING_PRICE,0),5),'FM990D00000'), 
      ADJI_FLEX_08 = to_CHAR(ROUND(nvl(R2.FG_AX_COST,0),5),'FM990D00000'),
      ADJI_FLEX_09 = to_CHAR(ROUND(nvl(R2.FG_AX_CONV_COST,0),5),'FM990D00000'),
      ADJI_FLEX_10 = to_CHAR(ROUND(nvl(R2.FG_VALUE_LOSS,0),5),'FM990D00000'),
      ADJI_FLEX_11 = to_CHAR(ROUND(nvl(R2.FG_PROD_VALUE_LOSS,0),5),'FM990D00000'),
      ADJI_FLEX_12 = R2.FG_MS_BATCH_ITEM
  WHERE ADJI_ITEM_CODE = R2.ADJI_ITEM_CODE
  AND ADJI_GRADE_CODE_1 = R2.ADJI_GRADE_CODE_1
   AND ADJI_GRADE_CODE_2 = R2.ADJI_GRADE_CODE_2
  AND ADJI_SYS_ID = R2.ADJI_SYS_ID;
  
 
  
END LOOP;

END;
/


-- approval transaksi di ERP

   update  OT_ADJ_HEAD 
   set ADJH_APPR_STATUS=3,
        ADJH_APPR_UID='SYSADMIN',
        ADJH_APPR_DT=SYSDATE
   WHERE 
   TRUNC(ADJH_DT) between '01-AUG-2026' AND '31-AUG-2026'
   AND ADJH_TXN_CODE IN ('INVADJ','MBINVADJ','MBINVADJRP')
   and ADJH_APPR_STATUS != 3
   and ADJH_SYS_ID not in (SELECT distinct ADJH_SYS_ID
                            FROM OT_ADJ_HEAD,OT_ADJ_ITEM
                               WHERE ADJI_ADJH_SYS_ID = ADJH_SYS_ID
                               AND TRUNC(ADJH_DT) between '01-AUG-2026' AND '31-AUG-2026'
                               AND ADJH_TXN_CODE IN ('INVADJ','MBINVADJ','MBINVADJRP')
                               AND NVL(ADJI_RATE,0) <= 0
                              and ADJH_APPR_STATUS != 3
                              )

