PROCEDURE        CHP_WAC_UPD
AS
M_CGCV_COST NUMBER;
M_CGCV_COST_BRT NUMBER;
M_CGCV_COST_FR NUMBER;
M_CGCV_COST_RCL NUMBER;
M_CGCV_COST_RCC NUMBER;
M_CGCV_COST_RCB NUMBER;
M_CGCV_COST_JIA NUMBER;
M_CGCV_COST_FD NUMBER;
M_CGCV_COST_BO NUMBER;

M_STD_CHP_COST NUMBER;
M_STD_CHP_COST_BRT NUMBER;
M_STD_CHP_COST_FR NUMBER;
M_STD_CHP_COST_RCL NUMBER;
M_STD_CHP_COST_RCC NUMBER;
M_STD_CHP_COST_RCB NUMBER;
M_STD_CHP_COST_JIA NUMBER;
M_STD_CHP_COST_FD NUMBER;
M_STD_CHP_COST_BO NUMBER;

M_QTY NUMBER;

M_CHIPS_TRANSP_COST NUMBER;

-- Written by jitendra IT MGT ,for update the stand costing table fo chip wac feild.
BEGIN

begin
select to_number(vssv_field_01) transp_cost
INTO M_CHIPS_TRANSP_COST
from IM_VS_STATIC_VALUE
where vssv_vs_code = 'CHP_TRN_COST'
and vssv_code = 'TRN_COST';
exception when no_data_found then
    M_CHIPS_TRANSP_COST := 0;
end;
/*
-- ADDED BY INDRA ON 31/10/18 TO GET CHIPS COST FOR FG VALUATION FROM CHIPS ISSUE NOT FROM CHIPS TOTAL WAC
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE in ('CHP0000033','CHP0000039')
    AND SL_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA','IRS','IRV')
);
--

IF M_CGCV_COST = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE in ('CHP0000033','CHP0000039')
    AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA','IRS','IRV');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE in ('CHP0000033','CHP0000039')
        AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA','IRS','IRV');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE in ('CHP0000033','CHP0000039')
        AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA','IRS','IRV');
    END IF;
END IF;

-- ADDED BY INDRA ON 31/10/18 TO GET CHIPS COST FOR FG VALUATION FROM CHIPS ISSUE NOT FROM CHIPS TOTAL WAC
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_BRT
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE = 'CHP0000034'
    AND SL_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA')
);
--
IF M_CGCV_COST_BRT = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE = 'CHP0000034'
    AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_BRT
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE = 'CHP0000034'
        AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_BRT
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000034')
        AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','TFI','NA');
    END IF;

END IF;

-- ADDED BY INDRA ON 31/10/18 TO GET CHIPS COST FOR FG VALUATION FROM CHIPS ISSUE NOT FROM CHIPS TOTAL WAC
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_FR
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE = 'CHP0000035'
    AND SL_GRADE_CODE_2 IN ('HCF','ZHE')
);
--
IF M_CGCV_COST_FR = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE = 'CHP0000035'
    AND CGCV_GRADE_CODE_2 IN ('HCF','ZHE');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_FR
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE = 'CHP0000035'
        AND CGCV_GRADE_CODE_2 IN ('HCF','ZHE');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_FR
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000035')
        AND CGCV_GRADE_CODE_2 IN ('HCF','ZHE');
    END IF;
END IF;

-- ADDED BY INDRA ON 31/10/18 TO GET CHIPS COST FOR FG VALUATION FROM CHIPS ISSUE NOT FROM CHIPS TOTAL WAC
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_RCL
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE IN ('CHP0000036','CHP0000037')
    AND SL_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','NA','TFI')
);
--
IF M_CGCV_COST_RCL = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE IN ('CHP0000036','CHP0000037')
    AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','NA','TFI');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_RCL
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000036','CHP0000037')
        AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','NA','TFI');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_RCL
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000036','CHP0000037')
        AND CGCV_GRADE_CODE_2 IN ('APF','IND','SLD','SPL','SGP','PLI','NA','TFI');
    END IF;

END IF;


-- ADDED BY INDRA ON 11/10/24 TO GET CHIPS COST FOR FG VALUATION FROM CHIPS ISSUE NOT FROM CHIPS TOTAL WAC FOR CHIPS RECYCLE FOR CARL WEISKE CUSTOMER
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_RCC
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE IN ('CHP0000036')
    AND SL_GRADE_CODE_2 IN ('IRV')
);
--
IF M_CGCV_COST_RCC = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE IN ('CHP0000036')
    AND CGCV_GRADE_CODE_2 IN ('IRV');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_RCC
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000036')
        AND CGCV_GRADE_CODE_2 IN ('IRV');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_RCC
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000036')
        AND CGCV_GRADE_CODE_2 IN ('IRV');
    END IF;

END IF;


-- ADDED BY INDRA ON 03/03/25 TO GET CHIPS COST FOR FG VALUATION FROM CHIPS ISSUE NOT FROM CHIPS TOTAL WAC FOR CHIPS RECYCLE FOR CARL WEISKE CUSTOMER
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_RCB
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE IN ('CHP0000040')
    AND SL_GRADE_CODE_2 IN ('IRS','IRV','ZHR')
);
--
IF M_CGCV_COST_RCB = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE IN ('CHP0000040')
    AND CGCV_GRADE_CODE_2 IN ('IRS','IRV','ZHR');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_RCB
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000040')
        AND CGCV_GRADE_CODE_2 IN ('IRS','IRV','ZHR');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_RCB
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000040')
        AND CGCV_GRADE_CODE_2 IN ('IRS','IRV','ZHR');
    END IF;

END IF;


-- ADDED BY INDRA ON 02/05/25 TO GET CHIPS COST FOR FG VALUATION FOR CHIPS JIA
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_JIA
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE IN ('CHP0000036')
    AND SL_GRADE_CODE_2 IN ('JIA','JIA-T2T')
);
--
IF M_CGCV_COST_JIA = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE IN ('CHP0000036')
    AND CGCV_GRADE_CODE_2 IN ('JIA','JIA-T2T');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_JIA
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000036')
        AND CGCV_GRADE_CODE_2 IN ('JIA','JIA-T2T');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_JIA
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000036')
        AND CGCV_GRADE_CODE_2 IN ('JIA','JIA-T2T');
    END IF;

END IF;

-- ADDED BY INDRA ON 02/02/2026 FOR ADDED FULL DULL CHIPS
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_FD
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'CHP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE IN ('CHP0000042')
    --AND SL_GRADE_CODE_2 IN ('IRV')
);
--
IF M_CGCV_COST_FD = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE IN ('CHP0000042');
    --AND CGCV_GRADE_CODE_2 IN ('IRV');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_FD
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000042');
        --AND CGCV_GRADE_CODE_2 IN ('IRV');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_FD
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('CHP0000042');
        --AND CGCV_GRADE_CODE_2 IN ('IRV');
    END IF;

END IF;


-- ADDED BY INDRA ON 02/02/2026 FOR ADDED FULL DULL CHIPS
SELECT CASE
            WHEN NVL(QTY,0) != 0 THEN ROUND(VAL / QTY,3)
            ELSE 0
        END
INTO M_CGCV_COST_BO
FROM
(
SELECT  SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000) QTY,
        SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END) VAL
    FROM OV_STOCK_LEDGER, OM_ITEM, OM_TXN
    WHERE SL_ITEM_CODE = ITEM_CODE
    AND ITEM_IG_CODE = 'RMP'
    AND SL_TXN_CODE = TXN_CODE
    AND TXN_TYPE IN ('MI','MR')
    AND SL_CONF_DT IS NOT NULL
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM')
    AND SL_ITEM_CODE IN ('RMP0000034','RMP0000043','RMP0000064')
    --AND SL_GRADE_CODE_2 IN ('IRV')
);
--
IF M_CGCV_COST_BO = 0 THEN
    SELECT NVL(SUM(CGCV_STK_QTY_BU/1000),0)
    INTO M_QTY
    FROM OS_COST_GROUP_CURR_VAL
    WHERE CGCV_ITEM_CODE IN ('RMP0000034','RMP0000043','RMP0000064');
    --AND CGCV_GRADE_CODE_2 IN ('IRV');

    IF NVL(M_QTY,0) <> 0 THEN
        SELECT ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),3)
        INTO M_CGCV_COST_BO
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('RMP0000034','RMP0000043','RMP0000064');
        --AND CGCV_GRADE_CODE_2 IN ('IRV');
    ELSE
        SELECT AVG(CGCV_COST_1)
        INTO M_CGCV_COST_BO
        FROM OS_COST_GROUP_CURR_VAL
        WHERE CGCV_ITEM_CODE IN ('RMP0000034','RMP0000043','RMP0000064');
        --AND CGCV_GRADE_CODE_2 IN ('IRV');
    END IF;

END IF;



  UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST =  ROUND(NVL(M_CGCV_COST,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'REG'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

 --END IF;


 --IF M_CGCV_COST_BRT <>M_STD_CHP_COST_BRT   THEN

  UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_BRT,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'BRT'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');


  UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_FR,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'FR'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

  UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_RCL,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'RCL'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

  UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_RCC,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'RCC'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

  UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_RCB,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'RCB'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

  UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_JIA,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'JIA'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_FD,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'FD'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

UPDATE OT_STD_COST_PRODUCTS_MGT
      SET FG_CHP_COST=  ROUND(NVL(M_CGCV_COST_BO,0),3) + NVL(M_CHIPS_TRANSP_COST,0)
      WHERE FG_ITEM_CODE IS NOT NULL
      AND FG_CHP_ITEM_CODE = 'BO'
      AND FG_ITEM_TYPE IN ('POY','PTY','ACY','ITY','TTY','HOY','TFY','TPY','TCY','TTS','TTM','TCS','TCM','PTS','PTM','TPM','ATY','ATT','LFG','TPS','NTY','TCH');

 --END IF;
*/

for i in
(
SELECT rmg_code,
       case
        when nvl(SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                END / 1000),0) = 0 then case
                                            when nvl(SUM(CGCV_STK_QTY_BU),0) = 0 then AVG(CGCV_COST_1)
                                            else ROUND(SUM(CGCV_VALUE_1)/SUM(CGCV_STK_QTY_BU/1000),4)
                                           end
        else NVL(SUM(CASE
                    WHEN SL_RCVD_ISSD = 'I' THEN SL_VAL_1
                    WHEN SL_RCVD_ISSD = 'R' THEN -SL_VAL_1
                  END),0) / NVL(SUM(CASE
                                WHEN SL_RCVD_ISSD = 'I' THEN SL_QTY_BU
                                WHEN SL_RCVD_ISSD = 'R' THEN -SL_QTY_BU
                            END / 1000),0)
       end rm_cost
from mgthris.RAW_MATERIAL_GROUP, mgthris.RAW_MATERIAL_ITEMS, OS_COST_GROUP_CURR_VAL,
    (SELECT SL_ITEM_CODE, SL_GRADE_CODE_1, SL_GRADE_CODE_2, SL_RCVD_ISSD, SL_QTY_BU, SL_VAL_1 FROM OS_STK_LEDGER
    WHERE SL_TXN_TYPE IN ('MI','MR')
    AND TO_CHAR(SL_DT,'RRRRMM') = TO_CHAR(ADD_MONTHS(SYSDATE,-1),'RRRRMM'))
where rmg_code = rmi_rmg_code
and RMI_ITEM_CODE = SL_ITEM_CODE (+)
and RMI_GRADE_1 = SL_GRADE_CODE_1 (+)
and RMI_GRADE_2 = SL_GRADE_CODE_2 (+)
and RMI_ITEM_CODE = CGCV_ITEM_CODE (+)
and RMI_GRADE_1 = CGCV_GRADE_CODE_1 (+)
and RMI_GRADE_2 = CGCV_GRADE_CODE_2 (+)
group by rmg_code
) loop


UPDATE OT_STD_COST_PRODUCTS_MGT
set FG_CHP_COST = i.rm_cost
where FG_CHP_ITEM_CODE = i.rmg_code;

end loop;

  COMMIT;

  END;
