PROCEDURE        STD_FG_COST_UPD_PRD AS

CURSOR C1 IS
SELECT DISTINCT ADJI_ITEM_CODE,
                --adji_item_desc, --remark by aam on 09 May 2016
                ADJI_GRADE_CODE_1,
                ADJI_GRADE_CODE_2
FROM OT_ADJ_HEAD,
     OT_ADJ_ITEM
WHERE ADJI_ADJH_SYS_ID=ADJH_SYS_ID
AND TRUNC(ADJH_DT) BETWEEN '01-JUL-2015' AND TRUNC(SYSDATE)
AND ADJH_TXN_CODE IN ('INVADJ','MBINVADJ','MBINVADJRP')
AND NVL(ADJI_RATE,0) <= 0
AND ADJH_POST_STATUS IS NULL
AND NOT EXISTS (SELECT * FROM OT_STD_COST_PRODUCTS_MGT
                WHERE ADJI_ITEM_CODE = FG_ITEM_CODE
                AND ADJI_GRADE_CODE_1 = FG_ITEM_GRADE
                AND ADJI_GRADE_CODE_2 = FG_ITEM_SHADE)
union
select DISTINCT SOI_ITEM_CODE,
                SOI_GRADE_CODE_1,
                SOI_GRADE_CODE_2
from ot_so_head, ot_so_item
where SOH_SYS_ID = soi_SOH_SYS_ID
and TRUNC(soh_DT) BETWEEN '01-JAN-2017' AND TRUNC(SYSDATE)
AND SOI_DNI_QTY_BU = 0
and SOH_TXN_CODE in ('STA','LSC')
AND NOT EXISTS (SELECT * FROM OT_STD_COST_PRODUCTS_MGT
                WHERE soI_ITEM_CODE = FG_ITEM_CODE
                AND soI_GRADE_CODE_1 = FG_ITEM_GRADE
                AND soI_GRADE_CODE_2 = FG_ITEM_SHADE);

BEGIN
    IF C1%ISOPEN THEN
        CLOSE C1;
    END IF;

    FOR R1 IN C1 LOOP
        MGTDAT.STD_FG_VALUE_INSERT(R1.ADJI_ITEM_CODE,R1.ADJI_GRADE_CODE_1,R1.ADJI_GRADE_CODE_2);
    END LOOP;
END;
