-- ODBTRG_COST_VAL_MGT ON OT_ADJ_HEAD | BEFORE EACH ROW | UPDATE
DECLARE

CURSOR C1 IS
   SELECT COUNT(*)
   FROM OT_ADJ_ITEM
   WHERE (NVL(ADJI_RATE,0)<=0 OR ADJI_RATE>20)
   AND SUBSTR(ADJI_ITEM_CODE,1,3) IN ('POY','PTY','ACY','ITY','MMK','TTY','HOY')
   AND ADJI_ADJH_SYS_ID=:NEW.ADJH_SYS_ID;

   M_COUNT  NUMBER;

BEGIN
IF :NEW.ADJH_APPR_STATUS=3  AND :NEW.ADJH_TXN_CODE IN ('INVADJ','SA') THEN
IF C1%ISOPEN THEN
  CLOSE C1;
 END IF;

 OPEN C1;
 FETCH C1 INTO M_COUNT;
 CLOSE C1;

 IF NVL(M_COUNT,0)!=0 THEN
 RAISE_APPLICATION('OP',241441,'','','','','','','','');
 END IF;
END IF;
 END;

-- ODBTRG_FG_STD_COST ON OT_STD_COST_PRODUCTS_MGT | BEFORE EACH ROW | INSERT OR UPDATE
DECLARE
    P_FLAG_FIXED_COST NUMBER := 0;
BEGIN
   IF :NEW.FG_ITEM_TYPE <> 'CMB' THEN

    IF :NEW.FG_BASIS = 'COST' THEN
	:NEW.FG_COST_PER_KG := ROUND((:NEW.FG_CHP_COST * :NEW.FG_CHP_CON_KG) + (:NEW.FG_CONVER_COST),5);
    ELSE
	:NEW.FG_COST_PER_KG := ROUND(:NEW.FG_SELLING_PRICE - :NEW.FG_VALUE_LOSS,5);
    END IF;

    if :NEW.FG_ITEM_GRADE = 'AX' and :NEW.FG_BASIS = 'COST' THEN
	:NEW.FG_CONVER_COST := ROUND(:NEW.FG_CONVER_COST,5);
	:NEW.FG_AX_CONV_COST := ROUND(:NEW.FG_CONVER_COST,5);
	:NEW.FG_SELLING_PRICE := 0;
	:NEW.FG_VALUE_LOSS := 0;
    END IF;

    :NEW.FG_AX_COST := ROUND((:NEW.FG_CHP_COST * :NEW.FG_CHP_CON_KG) + (:NEW.FG_AX_CONV_COST),5);
    :NEW.FG_PROD_VALUE_LOSS := ROUND(:NEW.FG_COST_PER_KG - :NEW.FG_AX_COST,5);
   END IF;
END;

