-- =====================================================================================
-- shipment_control_schema.sql — Shipment Control (Exim) reference DDL
--
-- ADVISORY ONLY. The Laravel migrations under
-- Modules/Finance/database/migrations/ are the source of truth; this file exists so a
-- DBA can review the shape, sizing and indexes in one place, and so the Oracle-only
-- objects (sequences, triggers, views) can be applied by hand in an environment where
-- migrations are disabled (DISABLE_MIGRATIONS).
--
-- Target: Oracle 11.2+ · schema MGTHRIS · see schema.md for the column rationale.
-- Sequence/PK convention follows LcControl: a BEFORE INSERT trigger calls
-- MGTHRIS.PKG_HM_SEQUENCES.get_next_seq_no.
-- Audit columns are the project standard: *_CREATED_BY / _CREATED_TIMESTAMP /
-- _MODIFIED_BY / _MODIFIED_TIMESTAMP.
-- =====================================================================================

-- ------------------------------------------------------------------ 1. MASTERS

CREATE TABLE MGTHRIS.SHIP_COST_TYPE (
  SHC_SYS_ID                 NUMBER          NOT NULL,
  SHC_CODE                   VARCHAR2(10)    NOT NULL,
  SHC_NAME                   VARCHAR2(100)   NOT NULL,
  SHC_DIRECTION              VARCHAR2(10)    NOT NULL,   -- EXPORT | IMPORT | BOTH
  SHC_JOURNAL_VOUCHER        VARCHAR2(20),               -- EPJV | IPJV
  SHC_BILL_VOUCHER           VARCHAR2(20),               -- EBJV | IBJV
  SHC_PAYMENT_VOUCHER        VARCHAR2(20),               -- ADVP | ADVP-EXP | BPS
  SHC_CLOSES_ON_CONFIRM      NUMBER(1)       DEFAULT 0 NOT NULL,
  SHC_REQUIRES_VENDOR        NUMBER(1)       DEFAULT 1 NOT NULL,
  SHC_REQUIRES_VENDOR_BANK   NUMBER(1)       DEFAULT 1 NOT NULL,
  SHC_FORCE_CURRENCY         VARCHAR2(3),
  SHC_FORCE_BANK_CODE        VARCHAR2(30),
  SHC_USES_DUTY_COLUMNS      NUMBER(1)       DEFAULT 0 NOT NULL,
  SHC_AUTO_PULL_TARIFF       NUMBER(1)       DEFAULT 0 NOT NULL,
  SHC_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SHC_CREATED_BY             VARCHAR2(30),
  SHC_CREATED_TIMESTAMP      TIMESTAMP,
  SHC_MODIFIED_BY            VARCHAR2(30),
  SHC_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_COST_TYPE PRIMARY KEY (SHC_SYS_ID),
  CONSTRAINT UQ_SHIP_COST_TYPE_CODE UNIQUE (SHC_CODE, SHC_DIRECTION)
);

CREATE TABLE MGTHRIS.SHIP_CONTAINER_TYPE (
  SHK_CODE                   VARCHAR2(20)    NOT NULL,
  SHK_NAME                   VARCHAR2(100)   NOT NULL,
  SHK_TEU                    NUMBER(9,2),
  SHK_REQUIRES_QTY           NUMBER(1)       DEFAULT 1 NOT NULL,   -- 0 for LCL
  SHK_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SHK_CREATED_BY             VARCHAR2(30),
  SHK_CREATED_TIMESTAMP      TIMESTAMP,
  SHK_MODIFIED_BY            VARCHAR2(30),
  SHK_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_CONTAINER_TYPE PRIMARY KEY (SHK_CODE)
);

-- The Pabean code is a STRING with a meaningful leading zero ('040300'), never a number.
CREATE TABLE MGTHRIS.SHIP_PORT (
  SHP_CODE                   VARCHAR2(20)    NOT NULL,   -- the Pabean code (legacy sah_flex_1)
  SHP_NAME                   VARCHAR2(100)   NOT NULL,   -- Pelabuhan (legacy sah_flex_2)
  SHP_OFFICE                 VARCHAR2(100),              -- KPU Bea dan Cukai | KPPBC
  SHP_OFFICE_TYPE            VARCHAR2(50),               -- A | C | Madya Pabean (no "Tipe" prefix)
  SHP_TRANSPORT_MODE         VARCHAR2(10)    DEFAULT 'SEA' NOT NULL,  -- SEA | AIR
  SHP_CITY                   VARCHAR2(100),
  SHP_IS_DEFAULT             NUMBER(1)       DEFAULT 0 NOT NULL,
  SHP_SORT_ORDER             NUMBER(3)       DEFAULT 0 NOT NULL,
  SHP_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SHP_CREATED_BY             VARCHAR2(30),
  SHP_CREATED_TIMESTAMP      TIMESTAMP,
  SHP_MODIFIED_BY            VARCHAR2(30),
  SHP_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_PORT PRIMARY KEY (SHP_CODE),
  CONSTRAINT CK_SHIP_PORT_MODE CHECK (SHP_TRANSPORT_MODE IN ('SEA','AIR'))
);

INSERT INTO MGTHRIS.SHIP_PORT
  (SHP_CODE, SHP_NAME, SHP_OFFICE, SHP_OFFICE_TYPE, SHP_TRANSPORT_MODE, SHP_CITY,
   SHP_IS_DEFAULT, SHP_SORT_ORDER, SHP_ACTIVE, SHP_CREATED_BY, SHP_CREATED_TIMESTAMP)
VALUES ('040300', 'Tanjung Priok', 'KPU Bea dan Cukai', 'A', 'SEA', 'Jakarta',
        1, 1, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MGTHRIS.SHIP_PORT
  (SHP_CODE, SHP_NAME, SHP_OFFICE, SHP_OFFICE_TYPE, SHP_TRANSPORT_MODE, SHP_CITY,
   SHP_IS_DEFAULT, SHP_SORT_ORDER, SHP_ACTIVE, SHP_CREATED_BY, SHP_CREATED_TIMESTAMP)
VALUES ('060100', 'Tanjung Emas', 'KPPBC', 'Madya Pabean', 'SEA', 'Semarang',
        0, 2, 1, 'SYSTEM', SYSTIMESTAMP);

INSERT INTO MGTHRIS.SHIP_PORT
  (SHP_CODE, SHP_NAME, SHP_OFFICE, SHP_OFFICE_TYPE, SHP_TRANSPORT_MODE, SHP_CITY,
   SHP_IS_DEFAULT, SHP_SORT_ORDER, SHP_ACTIVE, SHP_CREATED_BY, SHP_CREATED_TIMESTAMP)
VALUES ('050100', 'Soekarno-Hatta', 'KPU Bea dan Cukai', 'C', 'AIR', 'Tangerang',
        0, 3, 1, 'SYSTEM', SYSTIMESTAMP);
COMMIT;

CREATE TABLE MGTHRIS.SHIP_ACTIVITY (
  SHA_SYS_ID                 NUMBER          NOT NULL,
  SHA_CODE                   VARCHAR2(30)    NOT NULL,
  SHA_NAME                   VARCHAR2(200)   NOT NULL,
  SHA_DIRECTION              VARCHAR2(10)    NOT NULL,
  SHA_COST_TYPE              VARCHAR2(10),
  SHA_DEFAULT_QTY            NUMBER(18,4),
  SHA_PPN_PCT                NUMBER(18,6)    DEFAULT 0 NOT NULL,
  SHA_PPH_PCT                NUMBER(18,6)    DEFAULT 0 NOT NULL,
  SHA_EXPENSE_MAIN_ACNT      VARCHAR2(20),
  SHA_EXPENSE_SUB_ACNT       VARCHAR2(20),
  SHA_PROVISION_ACNT         VARCHAR2(20),
  SHA_SORT_ORDER             NUMBER(5)       DEFAULT 0 NOT NULL,
  SHA_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SHA_CREATED_BY             VARCHAR2(30),
  SHA_CREATED_TIMESTAMP      TIMESTAMP,
  SHA_MODIFIED_BY            VARCHAR2(30),
  SHA_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_ACTIVITY PRIMARY KEY (SHA_SYS_ID),
  CONSTRAINT UQ_SHIP_ACTIVITY UNIQUE (SHA_CODE, SHA_DIRECTION)
);

CREATE TABLE MGTHRIS.SHIP_TARIFF (
  SHT_SYS_ID                 NUMBER          NOT NULL,
  SHT_DIRECTION              VARCHAR2(10)    NOT NULL,
  SHT_VENDOR_CODE            VARCHAR2(30)    NOT NULL,   -- 'ALL' allowed (import)
  SHT_CONTAINER_TYPE         VARCHAR2(20),
  SHT_PORT_CODE              VARCHAR2(20),               -- NULL = any port
  SHT_ACTIVITY_CODE          VARCHAR2(30)    NOT NULL,
  SHT_SHAPE                  VARCHAR2(10)    NOT NULL,   -- TIER | FIX | FLAT
  SHT_TIER_GROUP             VARCHAR2(50),
  SHT_TIER_SEQ               NUMBER(3),
  SHT_MIN_QTY                NUMBER(18,4),
  SHT_MAX_QTY                NUMBER(18,4),
  SHT_RATE                   NUMBER(18,4)    DEFAULT 0 NOT NULL,
  SHT_CURRENCY               VARCHAR2(3)     NOT NULL,
  SHT_EXPENSE_MAIN_ACNT      VARCHAR2(20),
  SHT_EXPENSE_SUB_ACNT       VARCHAR2(20),
  SHT_PROVISION_ACNT         VARCHAR2(20),
  SHT_EFF_FROM               DATE,
  SHT_EFF_TO                 DATE,
  SHT_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SHT_CREATED_BY             VARCHAR2(30),
  SHT_CREATED_TIMESTAMP      TIMESTAMP,
  SHT_MODIFIED_BY            VARCHAR2(30),
  SHT_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_TARIFF PRIMARY KEY (SHT_SYS_ID),
  CONSTRAINT FK_SHIP_TARIFF_PORT FOREIGN KEY (SHT_PORT_CODE)
    REFERENCES MGTHRIS.SHIP_PORT (SHP_CODE)
);
CREATE INDEX MGTHRIS.IX_SHIP_TARIFF_LOOKUP
  ON MGTHRIS.SHIP_TARIFF (SHT_DIRECTION, SHT_VENDOR_CODE, SHT_PORT_CODE, SHT_CONTAINER_TYPE, SHT_ACTIVE);

CREATE TABLE MGTHRIS.SHIP_FACILITY (
  SHF_CODE                   VARCHAR2(30)    NOT NULL,
  SHF_NAME                   VARCHAR2(200),
  SHF_AUTO_REGISTERED        NUMBER(1)       DEFAULT 0 NOT NULL,
  SHF_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SHF_CREATED_BY             VARCHAR2(30),
  SHF_CREATED_TIMESTAMP      TIMESTAMP,
  SHF_MODIFIED_BY            VARCHAR2(30),
  SHF_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_FACILITY PRIMARY KEY (SHF_CODE)
);

CREATE TABLE MGTHRIS.SHIP_POSTING_ACCOUNT (
  SPA_SYS_ID                 NUMBER          NOT NULL,
  SPA_DIRECTION              VARCHAR2(10),
  SPA_DOCUMENT               VARCHAR2(20),               -- PROVISION | BILL
  SPA_COST_TYPE              VARCHAR2(10),
  SPA_ACTIVITY_CODE          VARCHAR2(30),
  SPA_PURPOSE                VARCHAR2(20)    NOT NULL,   -- EXPENSE|PROVISION|PPN|PPH|DUTY_*|BANK
  SPA_CONDITION              VARCHAR2(30),               -- PPN_1_1 | HAS_PPH | NO_PPH | ...
  SPA_MAIN_ACNT              VARCHAR2(20),
  SPA_SUB_ACNT               VARCHAR2(20),
  SPA_PRIORITY               NUMBER(3)       DEFAULT 100 NOT NULL,
  SPA_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SPA_CREATED_BY             VARCHAR2(30),
  SPA_CREATED_TIMESTAMP      TIMESTAMP,
  SPA_MODIFIED_BY            VARCHAR2(30),
  SPA_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_POSTING_ACCOUNT PRIMARY KEY (SPA_SYS_ID)
);
CREATE INDEX MGTHRIS.IX_SHIP_POSTING_ACNT_LOOKUP
  ON MGTHRIS.SHIP_POSTING_ACCOUNT (SPA_PURPOSE, SPA_DIRECTION, SPA_DOCUMENT, SPA_COST_TYPE, SPA_PRIORITY);

CREATE TABLE MGTHRIS.SHIP_PARAMETER (
  SHR_KEY                    VARCHAR2(60)    NOT NULL,
  SHR_VALUE                  VARCHAR2(500),
  SHR_VALUE_LONG             CLOB,
  SHR_DATA_TYPE              VARCHAR2(10)    DEFAULT 'STRING' NOT NULL,
  SHR_GROUP                  VARCHAR2(40),
  SHR_DESCRIPTION            VARCHAR2(500),
  SHR_ACTIVE                 NUMBER(1)       DEFAULT 1 NOT NULL,
  SHR_CREATED_BY             VARCHAR2(30),
  SHR_CREATED_TIMESTAMP      TIMESTAMP,
  SHR_MODIFIED_BY            VARCHAR2(30),
  SHR_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_PARAMETER PRIMARY KEY (SHR_KEY)
);

-- ------------------------------------------------------------------ 2. PROVISION

CREATE TABLE MGTHRIS.SHIP_PROVISION (
  SPV_SYS_ID                 NUMBER          NOT NULL,
  SPV_TRANS_NO               VARCHAR2(20)    NOT NULL,
  SPV_DIRECTION              VARCHAR2(10)    NOT NULL,   -- EXPORT | IMPORT
  SPV_TRANS_DATE             DATE            NOT NULL,
  SPV_STATUS                 NUMBER(1)       DEFAULT 0 NOT NULL,
  SPV_COST_TYPE              VARCHAR2(10)    NOT NULL,
  SPV_CUSTOMER_CODE          VARCHAR2(30),
  SPV_SUPPLIER_CODE          VARCHAR2(30),
  SPV_VENDOR_CODE            VARCHAR2(30),
  SPV_VENDOR_NAME            VARCHAR2(200),
  SPV_CURRENCY               VARCHAR2(3)     NOT NULL,
  SPV_EXCHANGE_RATE          NUMBER(18,6)    DEFAULT 1 NOT NULL,
  SPV_BANK_CURRENCY          VARCHAR2(3),
  SPV_IS_CROSS_CURRENCY      NUMBER(1)       DEFAULT 0 NOT NULL,
  SPV_BANK_CODE              VARCHAR2(30),
  SPV_VENDOR_BANK_NAME       VARCHAR2(200),
  SPV_VENDOR_BANK_ACC        VARCHAR2(100),
  SPV_VENDOR_BANK_NO         VARCHAR2(50),
  -- export documents
  SPV_SI_NO                  VARCHAR2(50),
  SPV_PEB_TYPE               VARCHAR2(50),
  SPV_DESTINATION            VARCHAR2(200),
  SPV_INCO_TERM              VARCHAR2(20),
  SPV_EIN_NO                 VARCHAR2(50),
  -- import documents
  SPV_PORT_CODE              VARCHAR2(20),               -- Pabean code, FK SHIP_PORT, drives the EMKL tariff
  SPV_PORT                   VARCHAR2(100),              -- Pelabuhan, free text, descriptive only
  SPV_SPTNP_NO               VARCHAR2(50),
  SPV_AJU_NO                 VARCHAR2(14),
  SPV_AJU_DATE               DATE,
  SPV_PIB_NO                 VARCHAR2(10),
  SPV_PIB_DATE               DATE,
  SPV_SPPB_NO                VARCHAR2(50),
  SPV_PL_NO                  VARCHAR2(50),
  SPV_BL_NO                  VARCHAR2(50),
  SPV_INVOICE_NO             VARCHAR2(50),
  SPV_INVOICE_DATE           DATE,
  -- reference
  SPV_REF_SYS_ID             NUMBER,
  SPV_DOC_REF                VARCHAR2(60),
  -- rollups
  SPV_TOTAL_BASE             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPV_TOTAL_PPN              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPV_TOTAL_PPH              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPV_TOTAL_FC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPV_TOTAL_LC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  -- vouchers
  SPV_PROV_DATE              DATE,
  SPV_PROV_VOUCHER           VARCHAR2(50),
  SPV_PROV_VOUCHER_DATE      DATE,
  SPV_PAY_DATE               DATE,
  SPV_PAY_VOUCHER            VARCHAR2(50),
  SPV_PAY_VOUCHER_DATE       DATE,
  SPV_REMARK                 VARCHAR2(500),
  -- workflow + audit
  SPV_SUBMITTED_BY           VARCHAR2(30),
  SPV_SUBMITTED_AT           TIMESTAMP,
  SPV_CONFIRMED_BY           VARCHAR2(30),
  SPV_CONFIRMED_AT           TIMESTAMP,
  SPV_LEGACY_SYS_ID          NUMBER,
  SPV_CREATED_BY             VARCHAR2(30),
  SPV_CREATED_TIMESTAMP      TIMESTAMP,
  SPV_MODIFIED_BY            VARCHAR2(30),
  SPV_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_PROVISION PRIMARY KEY (SPV_SYS_ID),
  CONSTRAINT UQ_SHIP_PROVISION_TRANS_NO UNIQUE (SPV_TRANS_NO),
  CONSTRAINT UQ_SHIP_PROVISION_LEGACY UNIQUE (SPV_LEGACY_SYS_ID),
  CONSTRAINT CK_SHIP_PROVISION_DIR CHECK (SPV_DIRECTION IN ('EXPORT','IMPORT')),
  CONSTRAINT FK_SHIP_PROVISION_REF FOREIGN KEY (SPV_REF_SYS_ID)
    REFERENCES MGTHRIS.SHIP_PROVISION (SPV_SYS_ID),
  CONSTRAINT FK_SHIP_PROVISION_PORT FOREIGN KEY (SPV_PORT_CODE)
    REFERENCES MGTHRIS.SHIP_PORT (SHP_CODE)
);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_PORT ON MGTHRIS.SHIP_PROVISION (SPV_PORT_CODE);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_DIR_STATUS ON MGTHRIS.SHIP_PROVISION (SPV_DIRECTION, SPV_STATUS, SPV_TRANS_DATE);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_AJU       ON MGTHRIS.SHIP_PROVISION (SPV_AJU_NO);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_SI        ON MGTHRIS.SHIP_PROVISION (SPV_SI_NO);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_VENDOR    ON MGTHRIS.SHIP_PROVISION (SPV_VENDOR_CODE);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_COSTTYPE  ON MGTHRIS.SHIP_PROVISION (SPV_COST_TYPE);

CREATE TABLE MGTHRIS.SHIP_PROVISION_INVOICE (
  SPI_SYS_ID                 NUMBER          NOT NULL,
  SPI_SPV_SYS_ID             NUMBER          NOT NULL,
  SPI_COST_TYPE              VARCHAR2(10)    NOT NULL,
  SPI_VENDOR_CODE            VARCHAR2(30)    NOT NULL,
  SPI_VENDOR_NAME            VARCHAR2(200),
  SPI_INVOICE_NO             VARCHAR2(50),
  SPI_INVOICE_DATE           DATE,
  SPI_CARRIER_NAME           VARCHAR2(200),
  SPI_CURRENCY               VARCHAR2(3)     NOT NULL,
  SPI_EXCHANGE_RATE          NUMBER(18,6)    DEFAULT 1 NOT NULL,
  SPI_TOTAL_BASE             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPI_TOTAL_PPN              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPI_TOTAL_PPH              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPI_TOTAL_FC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPI_TOTAL_LC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPI_TOTAL_CC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPI_LEGACY_SYS_ID          NUMBER,
  SPI_CREATED_BY             VARCHAR2(30),
  SPI_CREATED_TIMESTAMP      TIMESTAMP,
  SPI_MODIFIED_BY            VARCHAR2(30),
  SPI_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_PROV_INV PRIMARY KEY (SPI_SYS_ID),
  CONSTRAINT UQ_SHIP_PROV_INV UNIQUE (SPI_SPV_SYS_ID, SPI_COST_TYPE, SPI_VENDOR_CODE),
  CONSTRAINT UQ_SHIP_PROV_INV_LEGACY UNIQUE (SPI_LEGACY_SYS_ID),
  CONSTRAINT FK_SHIP_PROV_INV_HEAD FOREIGN KEY (SPI_SPV_SYS_ID)
    REFERENCES MGTHRIS.SHIP_PROVISION (SPV_SYS_ID) ON DELETE CASCADE
);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_INV_VENDOR ON MGTHRIS.SHIP_PROVISION_INVOICE (SPI_VENDOR_CODE);

CREATE TABLE MGTHRIS.SHIP_PROVISION_COST (
  SPC_SYS_ID                 NUMBER          NOT NULL,
  SPC_SPI_SYS_ID             NUMBER          NOT NULL,
  SPC_ACTIVITY_CODE          VARCHAR2(30)    NOT NULL,
  SPC_ACTIVITY_NAME          VARCHAR2(200),
  SPC_CONTAINER_TYPE         VARCHAR2(20),
  SPC_FACILITY_CODE          VARCHAR2(30),
  SPC_QTY                    NUMBER(18,4)    DEFAULT 0 NOT NULL,
  SPC_RATE                   NUMBER(18,4)    DEFAULT 0 NOT NULL,
  SPC_CURRENCY               VARCHAR2(3)     NOT NULL,
  SPC_PPN_PCT                NUMBER(18,6)    DEFAULT 0 NOT NULL,
  SPC_PPH_PCT                NUMBER(18,6)    DEFAULT 0 NOT NULL,
  SPC_PPH_ADVANCED           NUMBER(1)       DEFAULT 0 NOT NULL,
  SPC_BASE_AMOUNT            NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPC_PPN_AMOUNT             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPC_PPH_AMOUNT             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPC_FC_AMOUNT              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPC_LC_AMOUNT              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPC_CC_AMOUNT              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  SPC_IS_CROSS_CURRENCY      NUMBER(1)       DEFAULT 0 NOT NULL,
  SPC_DUTY_BM                NUMBER(18,2),
  SPC_DUTY_PPN               NUMBER(18,2),
  SPC_DUTY_PPH               NUMBER(18,2),
  SPC_EXPENSE_MAIN_ACNT      VARCHAR2(20),
  SPC_EXPENSE_SUB_ACNT       VARCHAR2(20),
  SPC_PROVISION_ACNT         VARCHAR2(20),
  SPC_PPN_ACNT               VARCHAR2(20),
  SPC_PPH_ACNT               VARCHAR2(20),
  SPC_SI_NO                  VARCHAR2(50),
  SPC_BL_NO                  VARCHAR2(50),
  SPC_REMARK                 VARCHAR2(500),
  SPC_TARIFF_SYS_ID          NUMBER,
  SPC_LEGACY_SYS_ID          NUMBER,
  SPC_CREATED_BY             VARCHAR2(30),
  SPC_CREATED_TIMESTAMP      TIMESTAMP,
  SPC_MODIFIED_BY            VARCHAR2(30),
  SPC_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_PROV_COST PRIMARY KEY (SPC_SYS_ID),
  CONSTRAINT UQ_SHIP_PROV_COST_LEGACY UNIQUE (SPC_LEGACY_SYS_ID),
  CONSTRAINT FK_SHIP_PROV_COST_INV FOREIGN KEY (SPC_SPI_SYS_ID)
    REFERENCES MGTHRIS.SHIP_PROVISION_INVOICE (SPI_SYS_ID) ON DELETE CASCADE
);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_COST_INV ON MGTHRIS.SHIP_PROVISION_COST (SPC_SPI_SYS_ID);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_COST_ACT ON MGTHRIS.SHIP_PROVISION_COST (SPC_ACTIVITY_CODE);

CREATE TABLE MGTHRIS.SHIP_PROVISION_CONTAINER (
  SPK_SYS_ID                 NUMBER          NOT NULL,
  SPK_SPV_SYS_ID             NUMBER          NOT NULL,
  SPK_CONTAINER_TYPE         VARCHAR2(20)    NOT NULL,
  SPK_QTY                    NUMBER(18,4)    DEFAULT 0 NOT NULL,
  SPK_LEGACY_SYS_ID          NUMBER,
  SPK_CREATED_BY             VARCHAR2(30),
  SPK_CREATED_TIMESTAMP      TIMESTAMP,
  SPK_MODIFIED_BY            VARCHAR2(30),
  SPK_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_PROV_CONT PRIMARY KEY (SPK_SYS_ID),
  CONSTRAINT UQ_SHIP_PROV_CONT UNIQUE (SPK_SPV_SYS_ID, SPK_CONTAINER_TYPE),
  CONSTRAINT FK_SHIP_PROV_CONT_HEAD FOREIGN KEY (SPK_SPV_SYS_ID)
    REFERENCES MGTHRIS.SHIP_PROVISION (SPV_SYS_ID) ON DELETE CASCADE
);

CREATE TABLE MGTHRIS.SHIP_PROVISION_DOC (
  SPD_SYS_ID                 NUMBER          NOT NULL,
  SPD_SPV_SYS_ID             NUMBER          NOT NULL,
  SPD_DOC_TYPE               VARCHAR2(10)    NOT NULL,   -- EDN | PO | SAMPLE
  SPD_DOC_NO                 VARCHAR2(50)    NOT NULL,
  SPD_ESC_NO                 VARCHAR2(50),
  SPD_STA_NO                 VARCHAR2(50),
  SPD_INVOICE_NO             VARCHAR2(50),
  SPD_PO_VALUE               NUMBER(18,2),
  SPD_INVOICED_VALUE         NUMBER(18,2),
  SPD_REMAINING_VALUE        NUMBER(18,2),
  SPD_MAIN_ACNT              VARCHAR2(20),
  SPD_LEGACY_SYS_ID          NUMBER,
  SPD_CREATED_BY             VARCHAR2(30),
  SPD_CREATED_TIMESTAMP      TIMESTAMP,
  SPD_MODIFIED_BY            VARCHAR2(30),
  SPD_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_PROV_DOC PRIMARY KEY (SPD_SYS_ID),
  CONSTRAINT UQ_SHIP_PROV_DOC UNIQUE (SPD_SPV_SYS_ID, SPD_DOC_TYPE, SPD_DOC_NO),
  CONSTRAINT FK_SHIP_PROV_DOC_HEAD FOREIGN KEY (SPD_SPV_SYS_ID)
    REFERENCES MGTHRIS.SHIP_PROVISION (SPV_SYS_ID) ON DELETE CASCADE
);
CREATE INDEX MGTHRIS.IX_SHIP_PROV_DOC_NO ON MGTHRIS.SHIP_PROVISION_DOC (SPD_DOC_NO);

-- ------------------------------------------------------------------ 3. SETTLEMENT (BILL)

CREATE TABLE MGTHRIS.SHIP_BILL (
  STL_SYS_ID                 NUMBER          NOT NULL,
  STL_TRANS_NO               VARCHAR2(20)    NOT NULL,
  STL_DIRECTION              VARCHAR2(10)    NOT NULL,
  STL_SOURCE                 VARCHAR2(10)    NOT NULL,   -- PROVISION | DIRECT
  STL_SPV_SYS_ID             NUMBER,
  STL_TRANS_DATE             DATE            NOT NULL,
  STL_BILL_DATE              DATE,
  STL_DUE_DATE               DATE,
  STL_STATUS                 NUMBER(1)       DEFAULT 0 NOT NULL,
  STL_COST_TYPE              VARCHAR2(10)    NOT NULL,
  STL_VENDOR_CODE            VARCHAR2(30),
  STL_VENDOR_NAME            VARCHAR2(200),
  STL_CURRENCY               VARCHAR2(3)     NOT NULL,
  STL_EXCHANGE_RATE          NUMBER(18,6)    DEFAULT 1 NOT NULL,
  STL_BANK_CURRENCY          VARCHAR2(3),
  STL_IS_CROSS_CURRENCY      NUMBER(1)       DEFAULT 0 NOT NULL,
  STL_BANK_CODE              VARCHAR2(30),
  STL_VENDOR_BANK_NAME       VARCHAR2(200),
  STL_VENDOR_BANK_ACC        VARCHAR2(100),
  STL_VENDOR_BANK_NO         VARCHAR2(50),
  STL_SI_NO                  VARCHAR2(500),
  STL_PEB_TYPE               VARCHAR2(50),
  STL_DESTINATION            VARCHAR2(200),
  STL_INCO_TERM              VARCHAR2(20),
  STL_EIN_NO                 VARCHAR2(500),
  STL_PORT_CODE              VARCHAR2(20),               -- Pabean code, FK SHIP_PORT
  STL_PORT                   VARCHAR2(100),              -- Pelabuhan, free text
  STL_AJU_NO                 VARCHAR2(14),
  STL_PIB_NO                 VARCHAR2(10),
  STL_BL_NO                  VARCHAR2(50),
  STL_TOTAL_BASE             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STL_TOTAL_PPN              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STL_TOTAL_PPH              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STL_TOTAL_FC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STL_TOTAL_LC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STL_TOTAL_CC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STL_TOTAL_DIFF             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STL_PAY_DATE               DATE,
  STL_BILL_VOUCHER           VARCHAR2(50),
  STL_BILL_VOUCHER_DATE      DATE,
  STL_PAY_VOUCHER            VARCHAR2(50),
  STL_PAY_VOUCHER_DATE       DATE,
  STL_REMARK                 VARCHAR2(500),
  STL_SUBMITTED_BY           VARCHAR2(30),
  STL_SUBMITTED_AT           TIMESTAMP,
  STL_CONFIRMED_BY           VARCHAR2(30),
  STL_CONFIRMED_AT           TIMESTAMP,
  STL_LEGACY_SYS_ID          NUMBER,
  STL_CREATED_BY             VARCHAR2(30),
  STL_CREATED_TIMESTAMP      TIMESTAMP,
  STL_MODIFIED_BY            VARCHAR2(30),
  STL_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_BILL PRIMARY KEY (STL_SYS_ID),
  CONSTRAINT UQ_SHIP_BILL_TRANS_NO UNIQUE (STL_TRANS_NO),
  CONSTRAINT UQ_SHIP_BILL_LEGACY UNIQUE (STL_LEGACY_SYS_ID),
  CONSTRAINT CK_SHIP_BILL_DIR    CHECK (STL_DIRECTION IN ('EXPORT','IMPORT')),
  CONSTRAINT CK_SHIP_BILL_SOURCE CHECK (STL_SOURCE IN ('PROVISION','DIRECT')),
  CONSTRAINT FK_SHIP_BILL_PROV FOREIGN KEY (STL_SPV_SYS_ID)
    REFERENCES MGTHRIS.SHIP_PROVISION (SPV_SYS_ID),
  CONSTRAINT FK_SHIP_BILL_PORT FOREIGN KEY (STL_PORT_CODE)
    REFERENCES MGTHRIS.SHIP_PORT (SHP_CODE)
);
CREATE INDEX MGTHRIS.IX_SHIP_BILL_DIR_STATUS ON MGTHRIS.SHIP_BILL (STL_DIRECTION, STL_STATUS, STL_BILL_DATE);
CREATE INDEX MGTHRIS.IX_SHIP_BILL_PROV       ON MGTHRIS.SHIP_BILL (STL_SPV_SYS_ID);
CREATE INDEX MGTHRIS.IX_SHIP_BILL_VENDOR     ON MGTHRIS.SHIP_BILL (STL_VENDOR_CODE);
CREATE INDEX MGTHRIS.IX_SHIP_BILL_DUE        ON MGTHRIS.SHIP_BILL (STL_DUE_DATE, STL_PAY_DATE);

CREATE TABLE MGTHRIS.SHIP_BILL_INVOICE (
  STI_SYS_ID                 NUMBER          NOT NULL,
  STI_STL_SYS_ID             NUMBER          NOT NULL,
  STI_COST_TYPE              VARCHAR2(10)    NOT NULL,
  STI_VENDOR_CODE            VARCHAR2(30)    NOT NULL,
  STI_VENDOR_NAME            VARCHAR2(200),
  STI_INVOICE_NO             VARCHAR2(50)    NOT NULL,
  STI_INVOICE_DATE           DATE,
  STI_RECEIVED_DATE          DATE,
  STI_CARRIER_NAME           VARCHAR2(200),
  STI_CURRENCY               VARCHAR2(3)     NOT NULL,
  STI_EXCHANGE_RATE          NUMBER(18,6)    DEFAULT 1 NOT NULL,
  STI_TOTAL_BASE             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STI_TOTAL_PPN              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STI_TOTAL_PPH              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STI_TOTAL_FC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STI_TOTAL_LC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STI_TOTAL_CC               NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STI_TOTAL_DIFF             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STI_LEGACY_SYS_ID          NUMBER,
  STI_CREATED_BY             VARCHAR2(30),
  STI_CREATED_TIMESTAMP      TIMESTAMP,
  STI_MODIFIED_BY            VARCHAR2(30),
  STI_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_BILL_INV PRIMARY KEY (STI_SYS_ID),
  CONSTRAINT UQ_SHIP_BILL_INV UNIQUE (STI_STL_SYS_ID, STI_INVOICE_NO),
  CONSTRAINT UQ_SHIP_BILL_INV_LEGACY UNIQUE (STI_LEGACY_SYS_ID),
  CONSTRAINT FK_SHIP_BILL_INV_HEAD FOREIGN KEY (STI_STL_SYS_ID)
    REFERENCES MGTHRIS.SHIP_BILL (STL_SYS_ID) ON DELETE CASCADE
);

CREATE TABLE MGTHRIS.SHIP_BILL_COST (
  STC_SYS_ID                 NUMBER          NOT NULL,
  STC_STI_SYS_ID             NUMBER          NOT NULL,
  STC_SPC_SYS_ID             NUMBER,
  STC_ACTIVITY_CODE          VARCHAR2(30)    NOT NULL,
  STC_ACTIVITY_NAME          VARCHAR2(200),
  STC_QTY                    NUMBER(18,4)    DEFAULT 1 NOT NULL,
  STC_RATE                   NUMBER(18,4)    DEFAULT 0 NOT NULL,
  STC_CURRENCY               VARCHAR2(3)     NOT NULL,
  STC_PPN_PCT                NUMBER(18,6)    DEFAULT 0 NOT NULL,
  STC_PPH_PCT                NUMBER(18,6)    DEFAULT 0 NOT NULL,
  STC_PPH_ADVANCED           NUMBER(1)       DEFAULT 0 NOT NULL,
  STC_BASE_AMOUNT            NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_PPN_AMOUNT             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_PPH_AMOUNT             NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_FC_AMOUNT              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_LC_AMOUNT              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_CC_AMOUNT              NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_IS_CROSS_CURRENCY      NUMBER(1)       DEFAULT 0 NOT NULL,
  STC_PROVISION_AMOUNT       NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_DIFF_AMOUNT            NUMBER(18,2)    DEFAULT 0 NOT NULL,
  STC_EXPENSE_MAIN_ACNT      VARCHAR2(20),
  STC_EXPENSE_SUB_ACNT       VARCHAR2(20),
  STC_PROVISION_ACNT         VARCHAR2(20),
  STC_PPN_ACNT               VARCHAR2(20),
  STC_PPH_ACNT               VARCHAR2(20),
  STC_FP_NO                  VARCHAR2(50),
  STC_FP_DATE                DATE,
  STC_EIN_NO                 VARCHAR2(50),
  STC_STA_NO                 VARCHAR2(50),
  STC_ESC_NO                 VARCHAR2(50),
  STC_SI_NO                  VARCHAR2(50),
  STC_INVOICE_NO             VARCHAR2(50),
  STC_REMARK                 VARCHAR2(500),
  STC_LEGACY_SYS_ID          NUMBER,
  STC_CREATED_BY             VARCHAR2(30),
  STC_CREATED_TIMESTAMP      TIMESTAMP,
  STC_MODIFIED_BY            VARCHAR2(30),
  STC_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_BILL_COST PRIMARY KEY (STC_SYS_ID),
  CONSTRAINT UQ_SHIP_BILL_COST_LEGACY UNIQUE (STC_LEGACY_SYS_ID),
  CONSTRAINT FK_SHIP_BILL_COST_INV FOREIGN KEY (STC_STI_SYS_ID)
    REFERENCES MGTHRIS.SHIP_BILL_INVOICE (STI_SYS_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SHIP_BILL_COST_PROV FOREIGN KEY (STC_SPC_SYS_ID)
    REFERENCES MGTHRIS.SHIP_PROVISION_COST (SPC_SYS_ID)
);
CREATE INDEX MGTHRIS.IX_SHIP_BILL_COST_INV ON MGTHRIS.SHIP_BILL_COST (STC_STI_SYS_ID);
CREATE INDEX MGTHRIS.IX_SHIP_BILL_COST_FP  ON MGTHRIS.SHIP_BILL_COST (STC_FP_NO);

CREATE TABLE MGTHRIS.SHIP_BILL_CONTAINER (
  STK_SYS_ID                 NUMBER          NOT NULL,
  STK_STL_SYS_ID             NUMBER          NOT NULL,
  STK_CONTAINER_TYPE         VARCHAR2(20)    NOT NULL,
  STK_QTY                    NUMBER(18,4)    DEFAULT 0 NOT NULL,
  STK_LEGACY_SYS_ID          NUMBER,
  STK_CREATED_BY             VARCHAR2(30),
  STK_CREATED_TIMESTAMP      TIMESTAMP,
  STK_MODIFIED_BY            VARCHAR2(30),
  STK_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_BILL_CONT PRIMARY KEY (STK_SYS_ID),
  CONSTRAINT UQ_SHIP_BILL_CONT UNIQUE (STK_STL_SYS_ID, STK_CONTAINER_TYPE),
  CONSTRAINT FK_SHIP_BILL_CONT_HEAD FOREIGN KEY (STK_STL_SYS_ID)
    REFERENCES MGTHRIS.SHIP_BILL (STL_SYS_ID) ON DELETE CASCADE
);

CREATE TABLE MGTHRIS.SHIP_BILL_DOC (
  STD_SYS_ID                 NUMBER          NOT NULL,
  STD_STL_SYS_ID             NUMBER          NOT NULL,
  STD_DOC_TYPE               VARCHAR2(10)    NOT NULL,
  STD_DOC_NO                 VARCHAR2(50)    NOT NULL,
  STD_ESC_NO                 VARCHAR2(50),
  STD_STA_NO                 VARCHAR2(50),
  STD_INVOICE_NO             VARCHAR2(50),
  STD_PO_VALUE               NUMBER(18,2),
  STD_INVOICED_VALUE         NUMBER(18,2),
  STD_REMAINING_VALUE        NUMBER(18,2),
  STD_MAIN_ACNT              VARCHAR2(20),
  STD_LEGACY_SYS_ID          NUMBER,
  STD_CREATED_BY             VARCHAR2(30),
  STD_CREATED_TIMESTAMP      TIMESTAMP,
  STD_MODIFIED_BY            VARCHAR2(30),
  STD_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_BILL_DOC PRIMARY KEY (STD_SYS_ID),
  CONSTRAINT UQ_SHIP_BILL_DOC UNIQUE (STD_STL_SYS_ID, STD_DOC_TYPE, STD_DOC_NO),
  CONSTRAINT FK_SHIP_BILL_DOC_HEAD FOREIGN KEY (STD_STL_SYS_ID)
    REFERENCES MGTHRIS.SHIP_BILL (STL_SYS_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------------ 4. BACKFILL BOOKKEEPING

CREATE TABLE MGTHRIS.SHIP_LEGACY_MAP (
  SLM_SYS_ID                 NUMBER          NOT NULL,
  SLM_ENTITY                 VARCHAR2(30)    NOT NULL,
  SLM_LEGACY_TABLE           VARCHAR2(30)    NOT NULL,
  SLM_LEGACY_SYS_ID          NUMBER          NOT NULL,
  SLM_NEW_SYS_ID             NUMBER          NOT NULL,
  SLM_RUN_ID                 VARCHAR2(40),
  SLM_CREATED_BY             VARCHAR2(30),
  SLM_CREATED_TIMESTAMP      TIMESTAMP,
  SLM_MODIFIED_BY            VARCHAR2(30),
  SLM_MODIFIED_TIMESTAMP     TIMESTAMP,
  CONSTRAINT PK_SHIP_LEGACY_MAP PRIMARY KEY (SLM_SYS_ID),
  CONSTRAINT UQ_SHIP_LEGACY_MAP UNIQUE (SLM_ENTITY, SLM_LEGACY_SYS_ID)
);

-- ------------------------------------------------------------------ 5. SEQUENCES + TRIGGERS
-- One sequence per table with a NUMBER PK. The trigger routes through
-- PKG_HM_SEQUENCES so the app and the database agree on how ids are handed out.
-- Repeat this pair for: SHIP_COST_TYPE(SHC), SHIP_ACTIVITY(SHA), SHIP_TARIFF(SHT),
-- SHIP_POSTING_ACCOUNT(SPA), SHIP_PROVISION(SPV), SHIP_PROVISION_INVOICE(SPI),
-- SHIP_PROVISION_COST(SPC), SHIP_PROVISION_CONTAINER(SPK), SHIP_PROVISION_DOC(SPD),
-- SHIP_BILL(STL), SHIP_BILL_INVOICE(STI), SHIP_BILL_COST(STC),
-- SHIP_BILL_CONTAINER(STK), SHIP_BILL_DOC(STD), SHIP_LEGACY_MAP(SLM).

CREATE SEQUENCE MGTHRIS.SHIP_PROVISION_SPV_SYS_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER MGTHRIS.SHIP_PROVISION_SYS_ID_TRG
  BEFORE INSERT ON MGTHRIS.SHIP_PROVISION
  FOR EACH ROW
  WHEN (NEW.SPV_SYS_ID IS NULL)
BEGIN
  :NEW.SPV_SYS_ID := MGTHRIS.PKG_HM_SEQUENCES.get_next_seq_no(
      p_seq_name    => 'SHIP_PROVISION_SPV_SYS_ID_SEQ',
      p_user_name   => 'SYSTEM',
      p_date_format => 'YYYY'
  );
END;
/

-- ------------------------------------------------------------------ 6. ORION VIEWS (read-only)

CREATE OR REPLACE VIEW MGTHRIS.V_SHIP_VENDOR AS
SELECT supp_code            AS vendor_code,
       supp_name            AS vendor_name,
       supp_flex_07         AS npwp_no,
       supp_flex_08         AS npwp_name,
       supp_flex_09         AS skb_no,
       supp_flex_10         AS skb_expiry
  FROM MGTDAT.OM_SUPPLIER;

CREATE OR REPLACE VIEW MGTHRIS.V_SHIP_CUSTOMER AS
SELECT cust_code            AS customer_code,
       cust_name            AS customer_name
  FROM MGTDAT.OM_CUSTOMER;

CREATE OR REPLACE VIEW MGTHRIS.V_SHIP_COMPANY_BANK AS
SELECT bad_main_acnt_code   AS bank_account_code,
       bad_bank_code        AS bank_code,
       bad_bank_acnt_no     AS bank_account_no,
       bad_curr_code        AS currency
  FROM MGTDAT.FM_BANK_ACNT_DETAIL;

-- Column names above are transcribed from the legacy documentation and MUST be
-- verified against the live MGTDAT dictionary before these views are created.

-- ------------------------------------------------------------------ 7. GUARDS (AFTER THE BACKFILL)
-- These enforce what the legacy app only checked in PHP. Create them only once the
-- backfill has run and data-migration.md §5 RED findings are resolved, otherwise they
-- will fail on legacy duplicates.

CREATE UNIQUE INDEX MGTHRIS.UX_SHIP_BILL_INV_VENDOR_INV
  ON MGTHRIS.SHIP_BILL_INVOICE (STI_VENDOR_CODE, UPPER(STI_INVOICE_NO));

CREATE UNIQUE INDEX MGTHRIS.UX_SHIP_BILL_COST_PROV_LINE
  ON MGTHRIS.SHIP_BILL_COST (STC_SPC_SYS_ID);
